version: "3.9"  # optional since v1.27.0
services:
  oracle:
    container_name: oracle
    image: gvenzl/oracle-xe:latest
    ports:
      - 1522:1521
    environment:
      ORACLE_PASSWORD: 123456
    volumes:
      - oracle-volume:/opt/oracle/oradata
    restart: always
    networks:
      - spring

  ms-usuarios:
    container_name: c-usuarios
    #image: usuarios
    build:
      context: ./
      dockerfile: ./ms-cursos/Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - ./ms-usuarios/.env
    networks:
      - spring
    depends_on:
      - oracle
    restart: always

  ms-cursos:
    container_name: c-cursos
    #image: cursos
    build:
      context: ./
      dockerfile: ./ms-cursos/Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - ./ms-cursos/.env
    networks:
      - spring
    depends_on:
      - oracle
    restart: always

volumes:
  oracle-volume:
    name: oracle-volume

networks:
  spring:
    name: spring